CONSTRUCT {
  <https://id.milieuinfo.be/dataset/imjv#id> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://rdfs.org/ns/void#Dataset> .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://www.w3.org/2000/01/rdf-schema#label> "IMJV"@nl .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://purl.org/dc/terms/title> "Dataset IMJV"@nl .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://purl.org/dc/terms/description> "Dataset Integraal Milieujaarverslag"@nl .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://purl.org/dc/terms/license> <https://dov.vlaanderen.be/dovweb/html/pdf/Gratis%20Open%20Data%20Licentie.pdf> .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#sparqlEndpoint> <https://id.milieuinfo.be/imjv/sparql> .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#exampleResource> ?dossier .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#exampleResource> ?document .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#exampleResource> ?activiteit .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#exampleResource> ?zuiveringsaparaat .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#exampleResource> ?emissie .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#exampleResource> ?emissiepunt .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#exampleResource> ?lozing .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#exampleResource> ?lozingspunt .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#feature> <http://www.w3.org/ns/formats/RDF_XML> .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#feature> <http://www.w3.org/ns/formats/Turtle> .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#feature> <http://www.w3.org/ns/formats/N-Triples> .
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#feature> <http://www.w3.org/ns/formats/JSON-LD> .
}
WHERE {
  {
    SELECT ?dossier
    WHERE {
      ?dossier <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Case> .
    }
    LIMIT 2
  }
  {
    SELECT ?document
    WHERE {
      ?document <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Document> .
    }
    LIMIT 2
  }
  {
    SELECT ?activiteit
    WHERE {
      ?activiteit <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Activity> .
    }
    LIMIT 2
  }
  {
    SELECT ?zuiveringsaparaat
    WHERE {
      ?zuiveringsaparaat <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Device> .
    }
    LIMIT 2
  }
  {
    SELECT ?emissie
    WHERE {
      ?emissie <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://id.milieuinfo.be/def#Emissie> .
    }
    LIMIT 2
  }
  {
    SELECT ?emissiepunt
    WHERE {
      ?emissiepunt <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://id.milieuinfo.be/def#Emissiepunt> .
    }
    LIMIT 2
  }
  {
    SELECT ?lozing
    WHERE {
      ?lozing <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://id.milieuinfo.be/def#GeleideLozing> .
    }
    LIMIT 2
  }
  {
    SELECT ?lozingspunt
    WHERE {
      ?lozingspunt <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://id.milieuinfo.be/def#Lozingspunt> .
    }
    LIMIT 2
  }
}