CONSTRUCT {
  <https://id.milieuinfo.be/dataset/gpbv#id> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://rdfs.org/ns/void#Dataset> .
  <https://id.milieuinfo.be/dataset/gpbv#id> <http://www.w3.org/2000/01/rdf-schema#label> "GPBV"@nl .
  <https://id.milieuinfo.be/dataset/gpbv#id> <http://purl.org/dc/terms/title> "Dataset GPBV"@nl .
  <https://id.milieuinfo.be/dataset/gpbv#id> <http://purl.org/dc/terms/description> "Dataset Preventie en Bestrijding van Verontreiniging"@nl .
  <https://id.milieuinfo.be/dataset/gpbv#id> <http://purl.org/dc/terms/license> <https://dov.vlaanderen.be/dovweb/html/pdf/Gratis%20Open%20Data%20Licentie.pdf> .
  <https://id.milieuinfo.be/dataset/gpbv#id> <http://rdfs.org/ns/void#sparqlEndpoint> <https://id.milieuinfo.be/gpbv/sparql> .
  <https://id.milieuinfo.be/dataset/gpbv#id> <http://rdfs.org/ns/void#exampleResource> ?installatie .
  <https://id.milieuinfo.be/dataset/gpbv#id> <http://rdfs.org/ns/void#feature> <http://www.w3.org/ns/formats/RDF_XML> .
  <https://id.milieuinfo.be/dataset/gpbv#id> <http://rdfs.org/ns/void#feature> <http://www.w3.org/ns/formats/Turtle> .
  <https://id.milieuinfo.be/dataset/gpbv#id> <http://rdfs.org/ns/void#feature> <http://www.w3.org/ns/formats/N-Triples> .
  <https://id.milieuinfo.be/dataset/gpbv#id> <http://rdfs.org/ns/void#feature> <http://www.w3.org/ns/formats/JSON-LD> .
}
WHERE {
  {
    SELECT ?installatie
    WHERE {
      ?installatie <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://id.milieuinfo.be/def#GpbvInstallatie> .
    }
    LIMIT 2
  }
}