CONSTRUCT {
  <https://id.milieuinfo.be/dataset/imjv#id> <http://purl.org/dc/terms/license> ?license .
}
WHERE {
  SELECT (<https://overheid.vlaanderen.be/gratis-open-data-licentie> AS ?license)
  { GRAPH ?g { ?s ?p ?o } } LIMIT 1
}

