CONSTRUCT {
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#uriLookupEndpoint> ?uriLookupEndpoint .
}
WHERE {
  SELECT (<https://id.milieuinfo.be/imjv/keywordsearch?search=> AS ?uriLookupEndpoint)
  { ?s ?p ?o } LIMIT 1
}
