
CONSTRUCT {
  <https://id.milieuinfo.be/dataset/imjv#id> <http://rdfs.org/ns/void#exampleResource> ?example .
}
WHERE {
  SELECT (SAMPLE(?s) as ?example) ?type {
    GRAPH ?g {
      ?s a ?type. FILTER (
          ?type NOT IN (
            <http://purl.org/linked-data/cube#AttributeProperty>,
            <http://purl.org/linked-data/cube#DimensionProperty>,
            <http://purl.org/linked-data/cube#MeasureProperty>,
            <http://rdf-vocabulary.ddialliance.org/xkos#ClassificationLevel>,
            <http://www.w3.org/2002/07/owl#Class>,
            <http://www.w3.org/2002/07/owl#DatatypeProperty>,
            <http://www.w3.org/2002/07/owl#FunctionalProperty>,
            <http://www.w3.org/2002/07/owl#NamedIndividual>,
            <http://www.w3.org/2002/07/owl#ObjectProperty>,
            <http://www.w3.org/2002/07/owl#Ontology>
          )
          && isIRI(?s)
          && (STRSTARTS(STR(?s), 'https://id.milieuinfo.be/') )
        )
    }
  }
  GROUP BY ?type
}

